### ISSUE TITLE
프로토타이핑

### ISSUE THREAD

**Issue by mitrvlr** [mitrvlr/playing-cards#2]
# 스택
- view : react
- store : recoil
- icons : react icons

# TODOS
- [ ] 전체 레이아웃 잡기
- [ ] 전체 테마적용
- [ ] 컴포넌트 설계

# 컴포넌트

## module
- [ ] 그룹 추가 버튼 → 그룹 생성 (추가된 그룹중에서 선택)
- [ ] 그룹 선택 리스트 (icon)
- [ ] 임직원 추가 버튼 (icon)

## layout
- [ ] sheet (make a map)
- [ ] sector (assign to locate)
